# Generated by Django 2.0.3 on 2018-03-24 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snowflake', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='nutritional_estimation',
        ),
    ]
