# Generated by Django 2.0.3 on 2018-03-26 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snowflake', '0002_remove_item_nutritional_estimation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
